### ISSUE TITLE
help，

### ISSUE THREAD

**Issue by searchknowledge** [DeepCar/Deepcar5.0#1]
I am currently studying your paper and there have been some issues with the reproduction that cannot be resolved. Could you please provide the source code? I hope you can reply to my information in your spare time. Thank you

**Comment by DeepCar** [comment]
Hello @searchknowledge 
Sorry for not getting back to you sooner!

**Comment by searchknowledge** [comment]
Dear Amir Hossein Barshooi:
       I am very glad to receive your letter.In my review of this paper, I
adopted the mode of yolov5 architecture in the object detection part. In
the training process,the accuracy obtained by each agent into the
corresponding classification network was 82.7%、93.81%、90.7% 、74.06%
respectively and The accuracy of the test set was 47.48%, 52.4%, 52% and
40% without using filter. I have always failed to reach the corresponding
accuracy in the original text. Have you ever had a similar situation in the
process of reproduction? In addition, when filter processing the  front
light  , it always fails to achieve the result in the original text. May I
ask whether the parameters of the front light filter and the uploaded file
are the same?In addition, can you provide the weights of the four networks
to see what can be achieved with the existing data set.
Finally,Wish you every success in the future.










DeepCar ***@***.***> 于2023年11月10日周五 16:01写道：

**Comment by searchknowledge** [comment]
Hello, I reproduce your article for the purpose of academic research. If possible, could you please provide me with a version for academic research? If the existing conditions cannot be met, may I ask whether you have conducted tests on the existing public data set? If possible, could you provide a test accuracy of each agent with and without filter as well as the fusion accuracy? Looking forward to your reply.

**Comment by searchknowledge** [comment]
Hello, I reproduce your article for academic research. If possible, could you please provide a latest version of the data set for academic research? If the existing conditions cannot be met, may I ask whether you have conducted tests on the existing public data set? If possible, could you provide a test accuracy of each agent with and without filter as well as the fusion accuracy? Looking forward to your reply.

**Comment by searchknowledge** [comment]
Hello, I reproduce your article for academic research. If possible, could you please provide a latest version of the data set for academic research, and can I pay for a paid license?  If the existing conditions cannot be met, may I ask whether you have conducted tests on the existing public data set? If possible, could you provide a test accuracy of each agent with and without filter as well as the fusion accuracy? Looking forward to your reply.
